todo_list/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("todo_list_app.urls", namespace="todo")),
]

todo_list_app/urls.py
from django.urls import path

from .views import (TaskListView,
                    TagListView,
                    TaskCreateView,
                    TagCreateView,
                    TagUpdateView,
                    TagDeleteView,
                    TaskUpdateView,
                    TaskDeleteView,
                    toggle_task_status)

urlpatterns = [
    path("", TaskListView.as_view(), name="task-list"),
    path("tags/", TagListView.as_view(), name="tag-list"),
    path("task/create/", TaskCreateView.as_view(), name="task-create"),
    path("tag/create/", TagCreateView.as_view(), name="tag-create"),
    path("tag/<int:pk>/update/", TagUpdateView.as_view(), name="tag-update"),
    path("task/<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("task/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path("tag/<int:pk>/delete/", TagDeleteView.as_view(), name="tag-delete"),
    path("<int:pk>/toggle-satus/", toggle_task_status, name="toggle-task-satus")
]

app_name = "todo"

todo_list_app/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=63)

    def __str__(self) -> str:
        return f"{self.name}"


class Task(models.Model):
    content = models.CharField(max_length=255)
    datetime = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(blank=True, null=True)
    is_done = models.BooleanField(default=False)
    tags = models.ManyToManyField(to=Tag)

    class Meta:
        ordering = ["is_done"]

todo_list_app/forms.py
from django import forms

from todo_list_app.models import Tag, Task


class TaskForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    deadline = forms.DateField(required=False, widget=forms.DateInput(attrs={"type": "date"}))

    class Meta:
        model = Task
        fields = ["content", "deadline", "tags"]


class TaskUpdateForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    deadline = forms.DateField(required=False, widget=forms.DateInput(attrs={"type": "date"}))

    class Meta:
        model = Task
        fields = ["content", "deadline", "is_done", "tags"]

todo_list_app/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from .forms import TaskForm, TaskUpdateForm

from todo_list_app.models import Task, Tag


# Create your views here.
class TaskListView(generic.ListView):
    model = Task
    queryset = Task.objects.prefetch_related("tags")
    template_name = "task/task_list.html"
    paginate_by = 5


class TagListView(generic.ListView):
    model = Tag
    template_name = "tag/tag_list.html"
    paginate_by = 5


class TaskCreateView(generic.CreateView):
    model = Task
    template_name = "task/task_form.html"
    form_class = TaskForm
    success_url = reverse_lazy("todo:task-list")


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    template_name = "tag/tag_form.html"
    success_url = reverse_lazy("todo:tag-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    template_name = "tag/tag_form.html"
    success_url = reverse_lazy("todo:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    template_name = "tag/tag_confirm_delete.html"
    success_url = reverse_lazy("todo:tag-list")


def toggle_task_status(request, pk: int) -> HttpResponseRedirect:
    task = Task.objects.get(id=pk)

    if task.is_done:
        task.is_done = False
        task.save()
    else:
        task.is_done = True
        task.save()
    return HttpResponseRedirect(reverse_lazy("todo:task-list"))


class TaskUpdateView(generic.UpdateView):
    model = Task
    form_class = TaskUpdateForm
    template_name = "task/task_form.html"
    success_url = reverse_lazy("todo:task-list")


class TaskDeleteView(generic.DeleteView):
    model = Task
    template_name = "task/task_confirm_delete.html"
    success_url = reverse_lazy("todo:task-list")

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}<title>To Do</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
          crossorigin="anonymous">
    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  <link rel="shortcut icon" href="/static/favicon.png" />
</head>

<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">

            {% block sidebar %}
                {% include "includes/sidebar.html" %}
            {% endblock %}

        </div>
        <div class="col-sm-10 ">

            {% block content %}{% endblock %}

            {% block pagination %}
                {% include "includes/pagination.html" %}
            {% endblock %}

        </div>
    </div>
</div>
</body>

</html>

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.previous_page_number %}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.next_page_number %}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item"><a href="{% url 'todo:task-list' %}">Home</a></li>
 <li class="list-group-item"><a href="{% url 'todo:tag-list' %}">Tags</a></li>
</ul>

templates/tag/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Are you sure that you want to delete tag {{ tag.name }}</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
  <br>
      <a href="{% url 'todo:tag-list' %}">
        <button class="btn btn-primary">No</button>
      </a>
{% endblock %}

templates/tag/tag_form.html
{% extends "base.html" %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} tag</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p}}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/tag/tag_list.html
{% extends "base.html" %}

{% block content %}
  <h1>Tags list</h1>
  <a href="{% url 'todo:tag-create' %}">
    <button class="btn btn-primary">Add tag</button>
  </a>
  <br><br><br>
  <div class="col-sm-8">
  <table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Action</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
  {% for tag in tag_list %}
    <tr>
      <th scope="row">{{ tag.id }}</th>
      <td>{{ tag.name}}</td>
      <td>
        <a href="{% url 'todo:tag-update' pk=tag.id %}">
          <button class="btn btn-secondary">Update</button>
        </a>
      </td>
      <td>
        <a href="{% url 'todo:tag-delete' pk=tag.id %}">
          <button class="btn btn-secondary">Delete</button>
        </a>
      </td>
    </tr>
    {% empty %}
    <p>There is no tags yet!</p>
  {% endfor %}
  </tbody>
  </table>
  </div>
{% endblock %}

templates/task/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Are you sure that you want to delete task {{ task.content }}</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
  <br>
      <a href="{% url 'todo:task-list' %}">
        <button class="btn btn-primary">No</button>
      </a>
{% endblock %}

templates/task/task_form.html
{% extends "base.html" %}



{% block content %}
  <h1>Create task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p }}

    <input type="submit" value="Submit" class="btn btn-primary">
{% endblock %}

templates/task/task_list.html
{% extends "base.html" %}

{% block content %}
  <h1>TODO list</h1>
  <a href="{% url 'todo:task-create' %}">
    <button class="btn btn-primary">Add task</button>
  </a>
  <br><br><br>
  <div class="col-sm-10">
  <table class="table">
  <thead>
    <tr>
      <th scope="col">Content</th>
      <th scope="col">Created</th>
      <th scope="col">Deadline</th>
      <th scope="col">Status</th>
      <th scope="col">Tags</th>
      <th scope="col">Action</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
  {% for task in task_list %}
    <tr>
      <th scope="row">
        <a href="{% url 'todo:task-update' pk=task.id %}">
          {{ task.content }}
        </a>
      </th>
      <td>{{ task.datetime }}</td>
      {% if task.deadline.date %}
      <td>{{ task.deadline.date }} {{ task.deadline.hour }}:{{ task.deadline.minute }}</td>
        {% else %}
        <td>no deadline</td>
      {% endif %}
        {% if task.is_done %}
          <td>done</td>
        {% else %}
          <td>in process</td>
        {% endif %}
      <td> {% for tag in task.tags.all %}
        {{ tag.name }}
        {% endfor %}
      </td>
    <td>
      {% if not task.is_done %}
        <a href="{% url 'todo:toggle-task-satus' pk=task.id %}">
          <button class="btn btn-success">Complete</button>
        </a>
      {% else %}
        <a href="{% url 'todo:toggle-task-satus' pk=task.id %}">
          <button class="btn btn-secondary">Undo</button>
        </a>
      {% endif %}
    </td>
    <td>

        <a href="{% url 'todo:task-delete' pk=task.id %}">
          <button class="btn btn-danger">Delete</button>
        </a>

    </td>
    </tr>
    {% empty %}
    <p>There is no tasks yet!</p>
  {% endfor %}
  </tbody>
  </table>
  </div>

{% endblock %}